### PR TITLE
Create rank_in_a_array.cpp

### PR DESCRIPTION
**Pull request by rajchaudhary99**
Sorting:- Copy and sort the original array to identify unique ranks.
Mapping:- Use an unordered map to assign ranks to unique elements.
Transforming:- Replace each element in the original array with its rank from the map.
Main Function:- Create a Solution instance, define an array, call the method, and print the results.

### CODE REVIEW

**Comment by Unnimaya6122004** [comment]
can u pls mention how your PR will be helpful for this repository @rajchaudhary99 ...

**Comment by Unnimaya6122004** [comment]
If u r aiming for hacktoberfest contribution....i have mentioned the steps in discussion...u can refer it

**Comment by rajchaudhary99** [comment]
@Unnimaya6122004 This PR optimizes the ranking algorithm for array transformation, ensuring better performance, cleaner code, and improved maintainability.

**Comment by Unnimaya6122004** [comment]
Okey..but this repository contains documentation...u just need to add new websites ,links which is helpful for everyone to access...there is no need of code...just edit the readme file..😇it is a beginner friendly repository

**Comment by rajchaudhary99** [comment]
thankyou @Unnimaya6122004

**Pull request closed without merging**
